spring:
  application:
    name: springcloud-consumer-numberSearch-feign-with-hystrix
server:
  port: 6602
eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123@localhost:6661/eureka
  instance:
    prefer-ip-address: true